theme: jekyll-theme-leap-day
title: [Python dasturlash tili]
description: [O'zbek tilida]
show_downloads: false
show_github_repository: false
show_description: true
show_visitors: true
is_theme_by: false

github:
  martianvenusian_url: https://martianvenusianorg.github.io
  home_url: https://martianvenusianorg.github.io/python_uz
  repository_name: [Python dasturlash tili]
